export const GEO_MATCH_SCORE = {
  ADDRESS_AND_STRONG_NAME: 82,
  CONTACT_AND_COMPATIBLE_NAME: 100,
  CONTACT_AND_FUZZY_NAME: 92,
  RAW_EXACT_NAME: 80,
  REDUCED_EXACT_NAME: 60,
  SHARED_GROUP_CONTACT_AND_STRONG_NAME: 84,
} as const;
