export enum GEO_MATCH_ACTION {
  ALREADY_MATCHED = 'ALREADY_MATCHED',
  AUTO_MATCHED = 'AUTO_MATCHED',
  CONFLICT = 'CONFLICT',
  MANUAL_GEO_SET = 'MANUAL_GEO_SET',
  MANUAL_MATCHED = 'MANUAL_MATCHED',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  NO_MATCH = 'NO_MATCH',
}
