export enum GEO_MATCH_REASON {
  ADDRESS_AND_STRONG_NAME = 'ADDRESS_AND_STRONG_NAME',
  CONTACT_AND_COMPATIBLE_NAME = 'CONTACT_AND_COMPATIBLE_NAME',
  CONTACT_AND_FUZZY_NAME = 'CONTACT_AND_FUZZY_NAME',
  OSM_DUPLICATE_BEST_CANDIDATE = 'OSM_DUPLICATE_BEST_CANDIDATE',
  RAW_EXACT_NAME = 'RAW_EXACT_NAME',
  REDUCED_EXACT_NAME = 'REDUCED_EXACT_NAME',
  SHARED_GROUP_CONTACT_AND_STRONG_NAME = 'SHARED_GROUP_CONTACT_AND_STRONG_NAME',
}
